### ISSUE TITLE
Default Format Drop-Down to "Unassigned"

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#105]
I think it would be best if we defaulted the drop-down to unassigned/no format.

There have been a few instances where users can't find some cards because they don't realize the default is currently set to "TCG". I think if we set the drop-down to default to no format users can find what they want more easily and they can then choose if they want a specific format.

Thoughts?

**Comment by FelixRilling** [comment]
Sounds good to me.
