### ISSUE TITLE
Add a search filter for card's description/effects

### ISSUE THREAD

**Issue by MKhayle** [FelixRilling/yugioh-deck-tool#116]
Hello,

It would be nice to be allowed to search for card effects/descriptions within the deck builder within the name search filter, especially to build more easily while using one's own collection. I know that kind of feature may require a heavy data load, though, so if that's not possible, I would understand.

Thanks in advance for considering this possibility, and for all your hard work.

**Comment by FelixRilling** [comment]
Hi!
Thanks for taking your time to file an issue.
I think that's actually not that hard - the description of a card is already loaded, just not used for anything besides the tooltip.
