### ISSUE TITLE
Hard to drag directly a card from the card list to the side deck

### ISSUE THREAD

**Issue by MKhayle** [FelixRilling/yugioh-deck-tool#117]
While searching for a precise card name, the list is short and rather high, and if my deck + extra are already filled a bit, I have to drag the card in the main deck, scroll down, and then drag it down from main deck to side deck. 

Example : 
![image](https://user-images.githubusercontent.com/4359469/133743665-4f65a855-601e-4d0a-8850-7d3dedc3dbf9.png)
![image](https://user-images.githubusercontent.com/4359469/133743969-505042e5-0262-48b3-9509-7db632d04be9.png)

It's a bit annoying, so I thought I could suggest putting the card list on a fixed position when scrolling down lower than its initial position. Of course, that's only UX issues, nothing important, please prioritize functional stuff over this ! 

Thanks a lot for your overall work.

**Comment by FelixRilling** [comment]
Hi, thanks for the input! Having a fixed position seems like a good idea, I will look into it.
