### ISSUE TITLE
Re-evaluate handling of decks in URI

### ISSUE THREAD

**Issue by FelixRilling** [FelixRilling/yugioh-deck-tool#137]
As suggested:

- remove compression of shareable link, as it provides very little actual advantage
- instead use YDKe-like encoding, to improve cross-application functionality

**Comment by kevinlul** [comment]
Suggestion: `ydke=main!extra!side!name`. This URL parameter and format will be shimmed by https://github.com/DawnbrandBots/deck-transfer-for-master-duel for the time being.

**Comment by kevinlul** [comment]
The next version of the extension will check for a `ydkeQueryString` flag and disable the shim https://github.com/DawnbrandBots/deck-transfer-for-master-duel/commit/5343125e0e64d0f6041f2b8bcf8757b5510e48d5. This will allow the deck builder to avoid redundancy if and when this is natively implemented :)

**Comment by FelixRilling** [comment]
> Suggestion: ydke=main!extra!side!name.
I am leaning towards keeping the name as a seperate query parameter, as it does not seem to be encoded in the YDKE URI by other tools, what are your thoughts on this?

**Comment by FelixRilling** [comment]
Progress in https://github.com/FelixRilling/yugioh-deck-tool/tree/feature/new-uri-deck

**Comment by kevinlul** [comment]
You're free to include the name after the third `!`, it works out.

**Comment by FelixRilling** [comment]
alright, so the current implementation is:
if the `y` query parameter is supplied, its content will be loaded as a deck.
the content is expected to be YDKE-data, followed by the deck name. the entire query parameter content should be URL encoded

**Comment by kevinlul** [comment]
Is this the idea? `y=${encodeURIComponent("ydke://main!extra!side!name")}`

**Comment by FelixRilling** [comment]
Almost, its only the data portion of the YDKE, so `y=${encodeURIComponent("main!extra!side!name")}`

**Comment by kevinlul** [comment]
FYI, the [released version of the extension](https://github.com/DawnbrandBots/deck-transfer-for-master-duel/releases/tag/1.2.0) this week no longer uses the shim and uses the native feature described here. Firefox, Chrome, Edge, and Safari clients should be switching over. Opera has yet to publish the version, but Opera users may have installed the Chrome version.
