### ISSUE TITLE
Integrate Google URL shortener API

### ISSUE THREAD

**Issue by FelixRilling** [FelixRilling/yugioh-deck-tool#15]

**Comment by FelixRilling** [comment]
Google requires an API key, would need to integrate into PHP backend.
Maybe just optimize current compression?

**Comment by AlanOC91** [comment]
The Bitly API might actually be real easy to use.

Here is a PHP example:
```
$long_url = urlencode('http://example.com/');

$bitly_login = 'username';
$bitly_apikey = 'YOUR API KEY';

$bitly_response = json_decode(file_get_contents("http://api.bit.ly/v3/shorten?login={$bitly_login}&apiKey={$bitly_apikey}&longUrl={$long_url}&format=json"));

$short_url = $bitly_response->data->url;
```

I signed up for an account and got a login and API key that's needed.
Although the Free plan is a little limited: 
![bitly](https://user-images.githubusercontent.com/37552458/54742292-e932d880-4bb8-11e9-8c9e-89d975622c4c.png)

Although 1000 links/month should be a lot in theory.
