### ISSUE TITLE
Problem with random deck generator + archetype

### ISSUE THREAD

**Issue by Zibokwe** [FelixRilling/yugioh-deck-tool#40]
I notice when I used 2-3 archetype, sometimes there's only 1 present, and every card in the deck is archetype card, most prominently with large archetypes like D/D/D and Gravekeeper.  maybe set a limit to how many cards can be in 1 archetype per ratio(or allow 60 card building, etc)? Other than that, absolutely love using this to get a basic idea for new decks to build.

**Comment by FelixRilling** [comment]
Hmm, thats a good point. Implementing a limit for the archetypes to avoid this problem sounds like a good idea, i'll look into it!

**Comment by FelixRilling** [comment]
4e68f84251088a0fb617c210e11c3b89c2a782fd
