### ISSUE TITLE
Add the ability to mass purchase a deck on TCGPlayer

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#42]
The TCGPlayer [Mass Entry tool](https://cart.tcgplayer.com/shoppingcart) allows you to pass a string query into it so bulk purchase a deck. 

Example format:

`https://store.tcgplayer.com/massentry?partner=YGOPRODeck&c=||1 Dark Magician||3 Time Wizard||2 Thousand Dragon||`

Parameters:

`?partner= ` - This is the partner ID code for the affiliate website.
`&c=` - These are the cards to be added into the tool.

The cards themselves must be between `||` and require a number before the card name.  I believe the number cannot come anywhere except before the card name. 

There may also be a parameter to set the default "**Product Line**" to "YuGiOh" but I haven't been able to accomplish this yet.

**Comment by FelixRilling** [comment]
Added in 4d5c27bf442c468fc8f0d12e04df244884dfe716
