### ISSUE TITLE
Add Archetype Drop-Down

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#43]
Similar to the "**Set**" drop down list.

Would it be possible to also add an Archetype one. When an archetype is selected is searches for cards that that have the selected archetype within their name/description.

Maybe it would also have to set the search text field to blank when an archetype is selected?

**Comment by FelixRilling** [comment]
It probably makes sense to use a multiselect for this, similar to the set selection.

**Comment by FelixRilling** [comment]
94dab3ad07b2af5aef922cbb71bc0db5c49644e0
