### ISSUE TITLE
Auto-Fill Official Tournament Form

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#44]
Have a button to potentially auto-fill an official tournament form based on the deck currently loaded into the deck builder.

Form example: [http://www.yugioh-card.com/en/events/forms/KDE_DeckList.pdf](http://www.yugioh-card.com/en/events/forms/KDE_DeckList.pdf)

**Comment by FelixRilling** [comment]
Need to check for image processing solutions.

**Comment by AlanOC91** [comment]
Potentially useful? https://github.com/pdffillerjs/pdffiller

**Comment by FelixRilling** [comment]
> Potentially useful? https://github.com/pdffillerjs/pdffiller

Sadly that does not seem to work in the browser

**Comment by FelixRilling** [comment]
-> with the new JS API to get the deck contents, I feel like this is something that can be implemented externally
