### ISSUE TITLE
& breaking mass purchase button

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#45]
& seems to be breaking entry into the mass purchase option for tcgplayer.

`Ash Blossom & Joyous Spring`

It will goes as far as "Ash Blossom" and stop inserting cards after that.

Example: https://ygoprodeck.com/card-database/deck-prices/?u=https://ygoprodeck.com/YGOPRO_Decks/3/22478.ydk

**Comment by FelixRilling** [comment]
Fixed with a4f2eeff1796707d75400445b14e9da7715e02a5
