### ISSUE TITLE
won't let me add more than three TOTAL cards to any given deck

### ISSUE THREAD

**Issue by fuzzy122672** [FelixRilling/yugioh-deck-tool#48]
as in, the max i can have is 3 in the main deck, 3 in the side, 3 in the extra. it doesn't matter the combination of cards. 
EDIT: pressing "Randomize" will net me a full deck, but if i remove a card, i still can't add another.

**Comment by AlanOC91** [comment]
This issue is fixed now. Bug when converting the deck.
