### ISSUE TITLE
Simplify card removal

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#50]
Some users seem to be having issues with removing cards from the deck builder on devices like an iPad.

https://ygoprodeck.com/Forum/viewtopic.php?f=6&t=2241&p=2986#p2986

Possibly add a physical button to remove cards from the currently built deck? 

Potentially:

1. A button that removes the most recently added card.

or 

2. A "-" symbol next to the card name that removes them.

This may be useful for making it only show on specific devices:

http://detectmobilebrowsers.com/

**Comment by FelixRilling** [comment]
With the new Drag & Drop based approach this can be done by "spilling" a card while dragging.
There is an open bug that this relies on though: https://github.com/SortableJS/Vue.Draggable/issues/827

**Comment by FelixRilling** [comment]
Related: #79

**Comment by FelixRilling** [comment]
Once https://github.com/SortableJS/Vue.Draggable/pull/886 is merged, this can be fixed

**Comment by FelixRilling** [comment]
Implemented workaround for 5.0.0

**Comment by FelixRilling** [comment]
Created follow-up, closing this one.
