### ISSUE TITLE
"Highlander" option for Deck Builder Randomize

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#53]
Had a request today from someone to implement a highlander option for the Deck Builder Randomize function.

Basically it makes a 60 card main deck and each card has to be unique. I'll look into the format more but that's the basics of it as far as I can tell.

**Comment by AlanOC91** [comment]
Yu-Gi-Oh! Highlander Format:

- Each card has to be unique, no duplicates!
- 60 cards main deck.
- 15 cards extra deck.

- Exclude the following: Skill Cards, Rush Duel Cards.

**Comment by FelixRilling** [comment]
aa5ac3085587a59ff5935ee14df047762f1cecbe 82f72d3d61d478010efd15ee994034f644f559c0
