### ISSUE TITLE
Add "OCG GOAT" as a new Format

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#55]
We recently added a new 2005 OCG GOAT format filter to our card database: https://db.ygoprodeck.com/search/?&format=OCG%20GOAT

Would be great if we could get this as a selection on our deck builder.

**Comment by FelixRilling** [comment]
Added the new format with 0f578e4f30fe20b9c49fa47077b45a45adff204e.
