### ISSUE TITLE
Randomizer creating decks with many duplicates

### ISSUE THREAD

**Issue by carbonox-infernox** [FelixRilling/yugioh-deck-tool#62]
![image](https://user-images.githubusercontent.com/27938083/78164965-9c631e00-7418-11ea-89e5-07dfadcdffbc.png)

**Comment by FelixRilling** [comment]
Hi! Do you mean the Cards with 3 or 2 copies  in the deck? that is intentional, to mimic the amount of cards in a "real" deck.
If you only want a single copy, #53 would be what you want I think (that feature is no in the public version of the deck tool yet through)

**Comment by FelixRilling** [comment]
The version with the new feature has been published; If any more questions exist, please re-open this issue
