### ISSUE TITLE
Button to Draft Deck

### ISSUE THREAD

**Issue by AlanOC91** [FelixRilling/yugioh-deck-tool#73]
I think it would be neat to have a button in the Deck Builder that will draft a deck for you.

Thankfully we have an API that will do just that!
 
So the API works as follows, calling the API will return the cards you drafted. It will choose a pack randomly from the 9 card pack pool. All rarity/pull logic is applied on the API end for accuracy. You can pass how many packs you'd like to open (so this can either be hard coded in or a user choice).

For example, to open 2 packs:
https://db.ygoprodeck.com/api/omega/pack-open.php?num=2

It returns a list of Card IDs and the Packs that were opened. 

You can also pass `&pack=battle` to only open Battle Packs. These packs have less cards in them but were designed for drafting. 
https://db.ygoprodeck.com/api/omega/pack-open.php?num=2&pack=battle

**Comment by FelixRilling** [comment]
-> with the new JS API to get the deck contents, I feel like this is something that can be implemented externally
