### ISSUE TITLE
Removing single cards from list broken

### ISSUE THREAD

**Issue by uberhalit** [FelixRilling/yugioh-deck-tool#92]
Since todays update rightclicking a card doesn't remove it from list anymore and dragging it out into a unoccupied area won't either. 
Tried with most recent Firefox and Chromium.

**Comment by meta3** [comment]
I can second that comment. It doesn't work. Regards

**Comment by FelixRilling** [comment]
Interesting - right clicking was intentionally removed in favor of drag & drop.
What happens when you drag a card outside the deck? does it just stay in the deck?
Can you add the contents of the console to this issue? (F12 -> Console -> Copy the content)

**Comment by meta3** [comment]
If I drag drop, nothing happens.

Console content:

jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
4app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 H'.
(anonymous) @ app.js:1
3app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 M'.
(anonymous) @ app.js:1
4app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
2app.js:1 Could not find set 'The Lost Art Promotion 2020 E'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Yu-Gi-Oh! 5D's Tag Force 5 Promotional Cards'.
(anonymous) @ app.js:1
2app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion O'.
(anonymous) @ app.js:1
5app.js:1 Could not find set 'The Lost Art Promotion 2020 G'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Maximum Gold'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Yu-Gi-Oh! 5D's Tag Force 5 Promotional Cards'.
(anonymous) @ app.js:1
4app.js:1 Could not find set 'Yu-Gi-Oh! Power of Chaos: Yugi the Destiny Limited Collector's Edition'.
(anonymous) @ app.js:1
3app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Remote Duel at Home Sweepstakes'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 F'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Yu-Gi-Oh! 5D's Wheelie Breakers promotional cards'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Trials of the Pharaoh - Trials of the Kingdom promotional card'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
2app.js:1 Could not find set 'Yu-Gi-Oh! 5D's Tag Force 5 Promotional Cards'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 I'.
(anonymous) @ app.js:1
2app.js:1 Could not find set 'Trials of the Pharaoh - Match of the Millennium & Twisted Nightmares promotional card'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 D'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Maximum Gold'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Yu-Gi-Oh! 5D's Wheelie Breakers promotional cards'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
2app.js:1 Could not find set 'Yu-Gi-Oh! Power of Chaos: Yugi the Destiny Limited Collector's Edition'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 D'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 G'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 P'.
(anonymous) @ app.js:1
2app.js:1 Could not find set '2020 Tin of Lost Memories'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'The Lost Art Promotion 2020 N'.
(anonymous) @ app.js:1
4app.js:1 Could not find set '2020 Tin of Lost Memories'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Maximum Gold'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'OTS Tournament Pack 13'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Eternity Code Premiere! promotional card'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Rise of the Duelist Premiere! promotional card'.
(anonymous) @ app.js:1
app.js:1 Could not find set 'Phantom Rage Premiere! promotional card'.
(anonymous) @ app.js:1
3app.js:1 Could not find set '2020 Tin of Lost Memories'.
(anonymous) @ app.js:1
app.js:18 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at app.js:18
    at new Promise (<anonymous>)
    at V (app.js:18)
    at s (app.js:40)
    at a.l (app.js:40)
    at change (app.js:40)
    at ne (app.js:5)
    at a.n (app.js:5)
    at ne (app.js:5)
    at a.t.$emit (app.js:5)
app.js:18 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at app.js:18
    at new Promise (<anonymous>)
    at V (app.js:18)
    at c (app.js:40)
    at a.l (app.js:40)
    at change (app.js:40)
    at ne (app.js:5)
    at a.n (app.js:5)
    at ne (app.js:5)
    at a.t.$emit (app.js:5)
3app.js:18 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at app.js:18
    at new Promise (<anonymous>)
    at V (app.js:18)
    at s (app.js:40)
    at a.l (app.js:40)
    at change (app.js:40)
    at ne (app.js:5)
    at a.n (app.js:5)
    at ne (app.js:5)
    at a.t.$emit (app.js:5)
ncmp-2024.min.js:8 Unknown CMP command: getConsentData
g @ ncmp-2024.min.js:8
app.js:18 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at app.js:18
    at new Promise (<anonymous>)
    at V (app.js:18)
    at c (app.js:40)
    at a.l (app.js:40)
    at change (app.js:40)
    at ne (app.js:5)
    at a.n (app.js:5)
    at ne (app.js:5)
    at a.t.$emit (app.js:5)
ncmp-2024.min.js:8 Unknown CMP command: getConsentData
g @ ncmp-2024.min.js:8
ap.lijit.com/www/sovrn_beacon_standalone/sovrn_standalone_beacon.js?iid=13401055:3 Uncaught TypeError: sovrn.auction.sovrnReady is not a function
ncmp-2024.min.js:8 Unknown CMP command: getVendorConsents
g @ ncmp-2024.min.js:8
static.adsafeprotected.com/sca.17.4.114.js:32 a: 0.003173828125 ms
ncmp-2024.min.js:8 Unknown CMP command: getConsentData
g @ ncmp-2024.min.js:8
3app.js:18 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at app.js:18
    at new Promise (<anonymous>)
    at V (app.js:18)
    at s (app.js:40)
    at a.l (app.js:40)
    at change (app.js:40)
    at ne (app.js:5)
    at a.n (app.js:5)
    at ne (app.js:5)
    at a.t.$emit (app.js:5)

**Comment by FelixRilling** [comment]
Fixed
