### ISSUE TITLE
Using old version

### ISSUE THREAD

**Issue by meta3** [FelixRilling/yugioh-deck-tool#94]
Hi,

is there any option to still use old version? I liked right click to remove cards, use interface was also quicker to use (there is more clicking for same effect right now, I don't liked "simulate start hand" in submenu, search card is also worse for me - I don't use browser in fullscreen, adding cards to deck/extra deck was also great with right click - if you don't have fullscreen its difficult to add cards in new version). My experience with new wesion is that I have to click a lot more then before. Visual look is great.

Kind regards

**Comment by FelixRilling** [comment]
Hi! 
Sadly the old version is no longer supported, but we can make changes to the current version to make it easier to to use:
- rightclicking could be added back, in addition to the drag & drop based system
- I'm unsure how to improve the access to the hand simulation - maybe add keyboard shortcuts for the menu entries?

Could you elaborate on the difficulties of adding cards? I am unsure how fullscreen has an effect on that

**Comment by AlanOC91** [comment]
- I think adding right click back in is also a good suggestion.
- I personally think the start hand simulator is fine under a sub-menu. Maybe Felix is on the right thought path with a keyboard shortcut for menu entries for accessibility. 
- Potentially add main, extra, side deck buttons back in, something like this:

![arrows](https://user-images.githubusercontent.com/37552458/95771148-79140800-0cb2-11eb-8529-67622f07e056.png)

This could work alongside drag/drop.

- Not sure how the searching is now worse. meta3 would need to elaborate on that. Seems fine to me. Maybe a quick keyboard shortcut to open the filter menu? This would allow for some fast keyboard searching. Keyboard shotcut to open the search menu and tab to go into the search bar.

If we do add keyboard shortcuts, maybe add some informational bar at the bottom of the builder to showcase this? Some sort of legend.

**Comment by meta3** [comment]
Hi,
First of all I really like your program and I use it for almost 2 years now. 

Before you had 3 buttons: add to main deck, add to side deck, add to extra. Now you have to drag card to this groups, it is more time consuming. If you have browser in window mode its difficult because you have to scroll down each time (I'm using it at work 😂, can't have it fullscreen). Search is worse only because you have to press 1 more button every time and then enter text (actual searching I think its much better in sens of searching word patterns). I use this program to build my test deck and I add/remove cards a lot. You probably meant that search is opened as long as you are adding cards.
Keyboard shortcuts would be awesome.

**Comment by FelixRilling** [comment]
Tracked in #95, #96 and #97.
 thank you for your feedback @meta3 , we will try to implement it for the final version!

Another question for your feedback on the search: do you mean the sidebar with more detailed filters? If so, I do not have a good idea on how that can be improved without reverting to the old design...

**Comment by meta3** [comment]
[https://ibb.co/dGYS1qq](url)

As you can see on image I have uploaded, because I use window mode, sidebar gets in the way (it covers "deck"). I have to close it after every search and re-open it when I search again. Before it didn't cover anything even in window mode and I had everything on my screen.

What about if you add one checkbox which would enable old "sidebar" if checked and new sidebar if unchecked (and save users decision to cookies)? You would had both but always hiding one of them. Would this be doable?

Kind regards

**Comment by FelixRilling** [comment]
Thanks for the feedback!
